
@startuml Diagramme de Classes
'projet'

class Kakarot{
    Initialise et lance Application ()
}
class ControleurKakarot {
    Orchestre vue et modele
}

Kakarot --> ControleurKakarot
ControleurKakarot --> modele.Plantes
ControleurKakarot --> vue.Vue
package modele <<Folder>> {
    class Jardinier{
        ajouter nouvelle plante ()
        supprimer plante ()
        rechercher plante ()
        afficher plante ()
        modifier plante ()
    }

    class Plantes{
        nom string
        catégories string 
        région string
        planter string
        recolter string
        astuce string
    }

    Plantes "n" *-->"1" Jardinier
   
}

package vue <<Folder>> {
    interface Vue {
        Interfaçage avec l'utilisateur.            
            Interfaçage graphique.
    }  
    interface Vue {
        RechercherVue()
        ModifierVue()
        SupprimerVue()
        AjouterVue()
    }

}


    


ControleurKakarot --> database.Plantes


@enduml
}
@enduml